// This file is automatically generated by Convex.

export const api = {
  zines: {
    createZine: 'zines:createZine',
    getZineByPublicId: 'zines:getZineByPublicId',
    getRecentZines: 'zines:getRecentZines',
    getUserZines: 'zines:getUserZines',
    searchZinesBySubject: 'zines:searchZinesBySubject',
    incrementShareCount: 'zines:incrementShareCount',
  },
  rateLimits: {
    checkRateLimit: 'rateLimits:checkRateLimit',
    recordRateLimitHit: 'rateLimits:recordRateLimitHit',
    migrateSession: 'rateLimits:migrateSession',
    cleanupExpiredRecords: 'rateLimits:cleanupExpiredRecords',
  },
};