// This file is automatically generated by Convex.

export const api = {
  zines: {
    createZine: 'createZine',
    getZineByPublicId: 'getZineByPublicId',
    getRecentZines: 'getRecentZines',
    getUserZines: 'getUserZines',
    searchZinesBySubject: 'searchZinesBySubject',
    incrementShareCount: 'incrementShareCount',
  },
  rateLimits: {
    checkRateLimit: 'checkRateLimit',
    recordRateLimitHit: 'recordRateLimitHit',
    migrateSession: 'migrateSession',
    cleanupExpiredRecords: 'cleanupExpiredRecords',
  },
} as const;