// This file is automatically generated by Convex.
// This is a simplified version for development purposes.

import { GenericId } from "convex/values";

export type Doc<TableName extends string = string> = {
  _id: GenericId<TableName>;
  _creationTime: number;
};

export type Id<TableName extends string = string> = GenericId<TableName>;