// This file is automatically generated by Convex.
// This is a simplified version for development purposes.

import { GenericId } from "convex/values";

export type Doc<TableName extends string = string> = {
  _id: GenericId<TableName>;
  _creationTime: number;
  [key: string]: any;
};

export type Id<TableName extends string = string> = GenericId<TableName>;

export { mutation, query, action, internalMutation, internalQuery, internalAction } from "convex/server";
export { v } from "convex/values";