/**
 * @fileoverview Curated subject suggestions for zine generation
 * Collection of creative, eclectic, and inspiring topics designed to showcase the AI's creative capabilities
 */

/**
 * Array of curated subject suggestions for random zine generation
 * 
 * @description Comprehensive collection of creative, unusual, and thought-provoking subjects:
 * - Blend of sci-fi, fantasy, cyberpunk, and surreal themes
 * - Designed to inspire creativity and demonstrate AI content generation capabilities  
 * - Topics range from whimsical to profound, ensuring diverse output possibilities
 * - Carefully selected to avoid controversial or potentially harmful content
 * - Each subject provides rich creative potential for zine-worthy content
 * 
 * @type {string[]} Array of subject strings (500 total subjects)
 * 
 * @usage Used by useSubjectForm hook for random subject selection
 * @example
 * ```typescript
 * import { SUBJECTS } from '@/app/constants';
 * 
 * const randomSubject = SUBJECTS[Math.floor(Math.random() * SUBJECTS.length)];
 * // e.g., "cyberpunk coffee" or "mystical mushrooms"
 * ```
 * 
 * @categories
 * - Cyberpunk/Tech: cyberpunk coffee, robotic fruit markets, AI sitcoms
 * - Fantasy/Magic: mystical mushrooms, witchcraft in metaverse, dragon roller derby  
 * - Sci-Fi/Space: lunar laundromats, intergalactic food trucks, alien pet adoption
 * - Post-Apocalyptic: post-apocalyptic knitting clubs, dystopian poetry slams
 * - Surreal/Abstract: time-traveling puppets, chaotic quantum jazz, feral disco balls
 * - Horror/Gothic: vampire rave etiquette, ghosts of abandoned malls, cosmic horror
 * - Retro/Vintage: steampunk submarine chronicles, retro-future love letters
 * 
 * @design
 * Subjects intentionally combine unexpected elements to:
 * - Challenge AI creativity and generate unique content
 * - Ensure zines are entertaining and engaging
 * - Provide safe, non-controversial content generation
 * - Demonstrate the versatility of AI-generated creative writing
 */
export const SUBJECTS = [
  "cyberpunk coffee",
  "mystical mushrooms",
  "time-traveling puppets",
  "radical skate diaries",
  "neon jungle nightlife",
  "robotic fruit markets",
  "interspecies diplomacy",
  "lunar laundromats",
  "the secret life of dinosaurs",
  "chaotic quantum jazz",
  "post-apocalyptic knitting clubs",
  "vampire rave etiquette",
  "steampunk submarine chronicles",
  "ghosts of abandoned malls",
  "intergalactic food trucks",
  "mermaid street racing",
  "cryptid survival guides",
  "parallel universe thrift shops",
  "dystopian poetry slams",
  "cosmic horror bar crawls",
  "pirates of the neon seas",
  "retro-future love letters",
  "alien pet adoption",
  "robotic plant care",
  "dragon roller derby",
  "artificial intelligence sitcoms",
  "forgotten gods of the arcade",
  "witchcraft in the metaverse",
  "punk rock botanists",
  "cyborg tea ceremonies",
  "underground jellyfish raves",
  "haunted typewriter confessions",
  "solar punk utopias",
  "feral disco balls",
  "mutant chef cook-offs",
  "subterranean library heists",
  "samurai in virtual reality",
  "lost cities of the deep web",
  "superhero therapy sessions",
  "gothic space operas",
  "time-lost disco kings",
  "alchemy in the apocalypse",
  "mythical creature internships",
  "vintage hologram collections",
  "galactic circus performers",
  "bioengineered fashion trends",
  "arcade noir mysteries",
  "philosophical android debates",
  "punk fairy godparents",
  "interdimensional food reviews",
  "cryptocurrency witch covens",
  "ravenous black hole recipes",
  "sentient spaceship romances",
  "holographic graffiti wars",
  "quantum labyrinth explorers",
  "haunted karaoke lounges",
  "the secret life of asteroids",
  "demonically possessed jazz clubs",
  "prehistoric cyborg adventures",
  "neon cathedral confessions",
  "cybernetic farm animals",
  "robot cowboy revolutions",
  "cloning experiments gone cute",
  "pirate radio transmissions from Mars",
  "urban legends in the singularity",
  "ghostly punk manifestos",
  "augmented reality scavenger hunts",
  "forgotten VR theme parks",
  "hacker cabaret chronicles",
  "space station soap operas",
  "enchanted forest rave reviews",
  "mecha wildlife documentaries",
  "alchemy and ska bands",
  "haunted train car diners",
  "cyborg dog walking businesses",
  "multiverse treasure hunters",
  "urban witch survival guides",
  "dystopian artisan bakeries",
  "laser tag philosophy",
  "astral projection tourism",
  "sci-fi speakeasy blueprints",
  "terraforming jazz festivals",
  "sentient fungi memoirs",
  "time-loop conspiracy zines",
  "punk dystopia matchmaking services",
  "floating city street photography",
  "hologram circus archives",
  "underground moon taverns",
  "alien bureaucracy exposés",
  "retro kaiju fashion shows",
  "digital ghost storytellers",
  "druid biker gangs",
  "futuristic minimalist cults",
  "spaceship flea markets",
  "robotic heirloom restorations",
  "AI-driven occult practices",
  "neon samurai poets",
  "secret societies of the void",
  "quantum babysitting services",
  "off-grid wizard communes",
  "holographic tarot readings",
  "post-human improv comedy troupes",
  "cyberpunk flower shops",
  "ghost pirates of the ethernet",
  "steampunk carnival rides",
  "augmented reality fashion shows",
  "robotic opera troupes",
  "time-lost oceanographers",
  "cosmic pastry chefs",
  "mythical beast motorbike clubs",
  "haunted VR escape rooms",
  "subterranean mushroom farms",
  "dystopian dating simulators",
  "punk zookeepers in space",
  "retro video game archaeologists",
  "alien megachurch sermons",
  "interdimensional buskers",
  "AI art crime rings",
  "cyborg monks of the wasteland",
  "phantom librarians of the void",
  "galactic street food wars",
  "solar-powered vampire hunters",
  "quantum graffiti movements",
  "pirate robots of the asteroid belt",
  "terraforming art collectives",
  "time-traveling culinary historians",
  "punk rock graveyard shifts",
  "sentient vending machines",
  "digital alchemy recipes",
  "underground asteroid mining crews",
  "neon knights of the cyber realm",
  "haunted algorithm programmers",
  "robotic stand-up comedians",
  "cyber-wizard biker gangs",
  "bioengineered houseplants",
  "steampunk treasure hunters",
  "witches of the neon sprawl",
  "time-looping stand-up comedy",
  "AI-written poetry slams",
  "ghosts of forgotten chatrooms",
  "punk mermaid tattoo artists",
  "alien board game designers",
  "cybernetic revolutionaries",
  "neon jungle conservationists",
  "robotic butterfly migrations",
  "underground hyperspace tunnels",
  "time-lost urban planners",
  "cyberpunk tarot decks",
  "dystopian pop-up diners",
  "cosmic puppetry workshops",
  "haunted urban spelunkers",
  "galactic DIY clubs",
  "post-apocalyptic jazz quartets",
  "parallel universe soap operas",
  "sentient elevator chronicles",
  "underground alien wrestling leagues",
  "punk dystopian cookbooks",
  "neon-drenched sushi wars",
  "cyberpunk fortune tellers",
  "robot dance battles",
  "interdimensional jazz fusion",
  "zombie startup culture",
  "quantum origami masters",
  "gothic cryptocurrency miners",
  "time-bending skateparks",
  "mecha butterfly collectors",
  "digital ghost hunters",
  "astral projection cafés",
  "sentient traffic lights",
  "underground robot boxing",
  "neon vampire nightclubs",
  "psychedelic coding bootcamps",
  "mutant food critic reviews",
  "cybernetic yoga instructors",
  "phantom stock traders",
  "alien smoothie recipes",
  "steampunk pizza delivery",
  "holographic pet grooming",
  "quantum barbershops",
  "haunted arcade repairs",
  "dystopian flower arranging",
  "time-traveling food bloggers",
  "robot poetry collectives",
  "cyberpunk kindergartens",
  "ghost ship cruise lines",
  "neon jungle gyms",
  "AI-powered fortune cookies",
  "mutant vegetable gardens",
  "interdimensional taxi services",
  "punk rock astronauts",
  "digital witchcraft tutorials",
  "robotic wine tasting",
  "cosmic horror knitting circles",
  "time-loop escape rooms",
  "cyborg fashion designers",
  "haunted streaming services",
  "quantum mechanics for cats",
  "alien language schools",
  "steampunk fitness centers",
  "neon wilderness guides",
  "post-apocalyptic book clubs",
  "sentient social networks",
  "underground meme dealers",
  "cyberpunk bird watching",
  "ghost town gentrification",
  "robotic massage parlors",
  "interdimensional real estate",
  "time-traveling historians",
  "mutant beauty pageants",
  "digital séance services",
  "cosmic barista championships",
  "haunted smartphone apps",
  "quantum dating algorithms",
  "alien street performers",
  "cybernetic gardening tips",
  "neon desert mirages",
  "robot rebellion manifestos",
  "ghost writer confessions",
  "steampunk weather stations",
  "interdimensional podcasts",
  "time-loop therapy groups",
  "mutant pet trainers",
  "digital dream interpreters",
  "cosmic bowling leagues",
  "haunted hotel reviews",
  "quantum particle zoos",
  "alien film festivals",
  "cyberpunk meditation retreats",
  "neon swamp creatures",
  "robot union negotiations",
  "ghost influencer scandals",
  "steampunk escape artists",
  "interdimensional cooking shows",
  "time-traveling tour guides",
  "mutant fashion weeks",
  "digital exorcism services",
  "cosmic karaoke battles",
  "haunted museum heists",
  "quantum physics for toddlers",
  "alien wedding planners",
  "cybernetic dance instructors",
  "neon tundra expeditions",
  "robot comedy clubs",
  "ghost town mayors",
  "steampunk submarine tours",
  "interdimensional mail service",
  "time-loop detective agencies",
  "mutant sports leagues",
  "digital afterlife planning",
  "cosmic ice cream trucks",
  "haunted theme park rides",
  "quantum computing cults",
  "alien daycare centers",
  "cyberpunk knitting patterns",
  "neon cave explorations",
  "robot philosophy debates",
  "ghost ship mechanics",
  "steampunk flying circuses",
  "interdimensional game shows",
  "time-traveling bartenders",
  "mutant music festivals",
  "digital personality backups",
  "cosmic tattoo parlors",
  "haunted office buildings",
  "quantum encryption poetry",
  "alien cooking competitions",
  "cybernetic life coaches",
  "neon aurora hunters",
  "robot rescue squads",
  "ghost economy analysts",
  "steampunk time machines",
  "interdimensional art galleries",
  "time-loop wedding planners",
  "mutant detective agencies",
  "digital consciousness uploads",
  "cosmic furniture stores",
  "haunted subway systems",
  "quantum entanglement dating",
  "alien standup comedians",
  "cyberpunk preschools",
  "neon coral reefs",
  "robot rights lawyers",
  "ghost story podcasts",
  "steampunk airship pirates",
  "interdimensional libraries",
  "time-traveling journalists",
  "mutant cooking shows",
  "digital soul merchants",
  "cosmic real estate bubbles",
  "haunted shopping malls",
  "quantum mechanics for dogs",
  "alien massage therapists",
  "cybernetic personal trainers",
  "neon mountain climbers",
  "robot jazz orchestras",
  "ghost town renovations",
  "steampunk detective agencies",
  "interdimensional plumbers",
  "time-loop vacation packages",
  "mutant hair salons",
  "digital dream dealers",
  "cosmic food trucks",
  "haunted parking garages",
  "quantum particle racing",
  "alien interior designers",
  "cyberpunk summer camps",
  "neon ocean explorers",
  "robot therapist sessions",
  "ghost writer workshops",
  "steampunk magic shows",
  "interdimensional delivery apps",
  "time-traveling archaeologists",
  "mutant talent shows",
  "digital meditation apps",
  "cosmic coffee roasters",
  "haunted car dealerships",
  "quantum computing cafés",
  "alien nail salons",
  "cybernetic bartenders",
  "neon prairie storms",
  "robot protest movements",
  "ghost economy trading",
  "steampunk roller coasters",
  "interdimensional dating apps",
  "time-loop insurance policies",
  "mutant food delivery",
  "digital prayer services",
  "cosmic thrift stores",
  "haunted music venues",
  "quantum physics dating",
  "alien yoga studios",
  "cyberpunk retirement homes",
  "neon volcano tourism",
  "robot soul searching",
  "ghost ship treasure hunts",
  "steampunk fashion police",
  "interdimensional uber drivers",
  "time-traveling teachers",
  "mutant makeover shows",
  "digital death certificates",
  "cosmic garage sales",
  "haunted cruise ships",
  "quantum particle pets",
  "alien cooking classes",
  "cybernetic wedding planners",
  "neon asteroid mining",
  "robot existential crisis",
  "ghost town tourism",
  "steampunk spy gadgets",
  "interdimensional customer service",
  "time-loop marriage counseling",
  "mutant reality TV",
  "digital reincarnation services",
  "cosmic furniture assembly",
  "haunted elevators",
  "quantum encryption recipes",
  "alien fashion advisors",
  "cyberpunk daycare centers",
  "neon glacier expeditions",
  "robot revolution recipes",
  "ghost influencer marketing",
  "steampunk theme parks",
  "interdimensional food critics",
  "time-traveling librarians",
  "mutant dating shows",
  "digital soul trading",
  "cosmic yard sales",
  "haunted airlines",
  "quantum particle therapy",
  "alien life coaches",
  "cybernetic sommeliers",
  "neon canyon races",
  "robot blues musicians",
  "ghost town festivals",
  "steampunk space stations",
  "interdimensional tech support",
  "time-loop birthday parties",
  "mutant cooking competitions",
  "digital afterlife insurance",
  "cosmic pawn shops",
  "haunted hospitals",
  "quantum computing bartenders",
  "alien personal shoppers",
  "cyberpunk nursing homes",
  "neon rainforest guardians",
  "robot improv troupes",
  "ghost ship restaurants",
  "steampunk time travelers",
  "interdimensional movers",
  "time-traveling chefs",
  "mutant modeling agencies",
  "digital soul downloads",
  "cosmic flea markets",
  "haunted universities",
  "quantum entanglement therapy",
  "alien tax advisors",
  "cybernetic nutritionists",
  "neon desert races",
  "robot slam poetry",
  "ghost economy crashes",
  "steampunk music festivals",
  "interdimensional lawyers",
  "time-loop retirement planning",
  "mutant game shows",
  "digital consciousness mergers",
  "cosmic antique dealers",
  "haunted train stations",
  "quantum physics for babies",
  "alien relationship counselors",
  "cyberpunk elementary schools",
  "neon arctic adventures",
  "robot labor unions",
  "ghost town hipsters",
  "steampunk cooking shows",
  "interdimensional accountants",
  "time-traveling bloggers",
  "mutant fitness trainers",
  "digital dream architects",
  "cosmic auction houses",
  "haunted airports",
  "quantum particle playgrounds",
  "alien hair stylists",
  "cybernetic therapists",
  "neon savanna safaris",
  "robot folk singers",
  "ghost ship salvage crews",
  "steampunk circuses",
  "interdimensional influencers",
  "time-loop travel agents",
  "mutant art critics",
  "digital soul repairs",
  "cosmic convenience stores",
  "haunted casinos",
  "quantum computing priests",
  "alien fitness instructors",
  "cyberpunk high schools",
  "neon reef diving",
  "robot protest songs",
  "ghost economy booms",
  "steampunk operas",
  "interdimensional janitors",
  "time-traveling photographers",
  "mutant dance crews",
  "digital personality trades",
  "cosmic hardware stores",
  "haunted restaurants",
  "quantum entanglement weddings",
  "alien child psychologists",
  "cybernetic veterinarians",
  "neon valley communes",
  "robot civil rights",
  "ghost town developers",
  "steampunk airlines",
  "interdimensional babysitters",
  "time-loop job interviews",
  "mutant cooking schools"
];
